### ISSUE TITLE
TODO List:

### ISSUE THREAD

**Issue by BPalhano** [ruanpereira/Arch_EXP#2]
Hello everynyan. (~How are you? fine, thank you~)

This issue is a to-do list for this repository, if you found this page and would like a tutorial for some software or tool, post your request here and we'll see what we can do! 
Thanks to all.

**Comment by BPalhano** [comment]
There are several redundant files, such as ```testing_org.org``` and the ```installation_guide.md``` on the home page. You need to clean them up @ruanpereira

**Comment by ruanpereira** [comment]
Done. Also, for cleaning and organization. Need to add:
- [x] Table of contents of the repo and link them to the respective Directory.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- [ ] Finish the Repo README with my thoughts, as follows:
- [x] Add the definition of DE and WM
- [x] Add the DE PROS AND CONS
- [x] Add DE tested and my opinion about it.
- [ ] Add best DE and why.
- [x] Add WM PROS AND CONS
- [x] Add WM tested and my opinion about it.
- [x] Add Next VM to test.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- [ ] Add a section with by best build momentaneously.
- [x] Review installation guide of i3  
- [x] Review installation guide of KDE.
- [x] Review packages of i3 (both aur and pacman).
- [x] Review packages of KDE (both aur and pacman).
- [x] Finish troubleshooting for i3.
- [ ] Add a section for games. (Stationary, but i feel like would be cool to advertise and annotate the actual state.)
- [x] Maybe a programming Directory in the futury? Or web dev.

**Comment by BPalhano** [comment]
about web dev and programming, gime this shit >:)

**Comment by ruanpereira** [comment]
the programming and webdev will be inside the Programs dir, until i have more things.

**Comment by ruanpereira** [comment]
development repository incoming

**Comment by BPalhano** [comment]
I would like to suggest to generate a document explaining why  the Arch does not have compatibility with scientific tools (e.g. Matlab, Ansys, etc). As far I know, there is no interest in the development companies to enable the compatibility, but I'm wondering why.
